variable "virtual_network_name" {}
variable "sql_virtual_network_name" {}
variable "virtual_network_address_space" {}
variable "subnet_name" {}
variable "sql_subnet_name" {}
variable "subnet_address" {}
variable "resource_group_name" {}
variable "resource_group_location" {}
variable "aks_cluster_name" {}
variable "aks_cluster_dns_prefix" {}
variable "client_id" {}
variable "client_secret" {}
variable "environment" {}
variable "sql_server_name" {}
variable "administrator_login" {}
variable "administrator_login_password" {}
variable "sql_firewall_rule_name" {}
variable "start_ip_address" {}
variable "end_ip_address" {}