variable virtual_network_name {}
variable virtual_network_address_space {}
variable subnet_name {}
variable subnet_address {}
variable resource_group_name {}
variable resource_group_location {}
variable aks_cluster_name {}
variable aks_cluster_dns_prefix {}
variable client_id {}
variable client_secret {}
variable environment {}